### ISSUE TITLE
High Reynolds Cylinder Simulations: YAML Issue

### ISSUE THREAD

**Issue by Chaztikov** [barbagroup/cuIBM#30]
Hi and thanks for your work on this!

I successfully ran the examples for Re<200, but seem to run into the following issue for the Re=550 and Re=3000 cases:

Parsing YAML file with simulation parameters ...
Parsing YAML file with flow conditions ...
terminate called after throwing an instance of 'YAML::InvalidNode'
  what():  invalid node; this may result from using a map iterator as a sequence iterator, or vice-versa
Aborted (core dumped)

Any idea how to fix this?   Thanks again.

**Comment by mesnardo** [comment]
Hi @Chaztikov 

Thank you for reporting this issue.

I recently updated the version of YAML-CPP from 0.5.1 to 0.5.3.
With 0.5.3, YAML-CPP throws an error when a key is not found in the .yaml configuration file and does not used the default value.
This issue was not present when we used version 0.5.1 (i.e., if a key is not found, we set a default value).

I pushed a new branch `hotfix-0.1.1`.
Can you let me know if this solves your issue?

**Comment by mesnardo** [comment]
I have downgraded the yaml-cpp version to 0.5.1 and merged the PR into the master branch.

**Comment by Chaztikov** [comment]
Thanks for the swift response, this works!
